config/routes.rb
Rails.application.routes.draw do



  resources :products
  root 'welcome#index'

  get 'welcome', to: 'welcome#index', as: 'welcome'
  get 'about', to: 'welcome#about', as: 'about'
  get 'contact', to: 'welcome#contact_us', as: 'contact'
  get 'prices', to: 'welcome#prices', as: 'prices'

  # get 'inicio', to: 'blog#index', as: 'inicio'
  # get 'new', to: 'blog#new', as: 'new'
  # get 'show', to: 'blog#show', as: 'show'
  # get 'edit', to: 'blog#edit', as: 'edit'

  # get 'blog/index', as: 'inicio'
  # get 'blog/new', as: 'new'
  # get 'blog/show', as: 'show'
  # get 'blog/edit', as: 'edit'

  resources :blog  #para crear el CRUD crea todas las url
  #resources :blog, only: [:index, :show, :edit] se limita para que solo muestre las rutas que le especifico
  #resources :blog, except: [:new] mostrar todas menos las listadas


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country, presence: true
  validates :name, length: { minimum: 3 }

  has_many :houses #siempre que se haga un reference, se debe agregar lo que contiene, has_many y belongs_to, el belong va en el modelo diceindo q pertenece a otro y el has_many en el modelo q lo tiene 
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :user
  belongs_to :city
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :tittle, :content, presence: true

  belongs_to :user
end


### antes
# post.create(tittle: "titulo")
# post.create!(tittle: "titulo")  // ! --> me muestra los errores...

###durante
# post = Post.new(tittle:"")
# post.save!

###despues
# post = Post.find(1)
# post.update(tittle: "")

#si no tenia el validador creado y alguien habia subido registros sin titulo por ejemplo...
# post = Post.find(2)
# post.valid?  resultado FALSE
# post.invalid? resultado TRUE

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  #validates :email, format: {width: add expresion regular...}
  validates :phone, numericality: true
  #tambien asi:
  #validate :phone, numericality: {only_integer: true}
  #validate :phone, numericality: {greater_than_or_equal_to: 10}

  has_many :houses
  has_many :posts
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  ## todo lo q pponga acá aplica para todos los demas controladores
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  #como el id se repite en todos esto se hace un callback... se define en los privados

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
    ##tittle y content se renderizan vacios
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blog_index_path, notice: "el blog ha sido guardado exitosamente"
      #flash[:alert] para error
      #flash[:notice] = "el blog ha sido guardado exitosamente"
      #flash[:message] = "el blog ha sido guardado exitosamente"
    else
      flash[:alert] = "el post no ha sido guardado, intente nuevamente"
      render :new
    end
  end

  def show
    #@blog = Blog.find(params[:id]) <-- lo estamos definiendo en el callback
  end

  def edit
    #@blog = Blog.find(params[:id]) <-- lo estamos definiendo en el callback
  end

  def update
    #@blog = Blog.find(params[:id]) <-- lo estamos definiendo en el callback

    if @blog.update(blog_params)
      redirect_to blog_index_path
    else
      render :edit
    end
  end

  def destroy
    #blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to blog_index_path
    flash[:alert] = "la entrada se ha eliminado"
  end

private
  def blog_params
    params.require(:blog).permit(:tittle, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "mi nombre es camilo..."
  end

  def about
    redirect_to prices_path
  end
 
  def contact_us

  end

  def prices

  end

#vistas / metodos / acciones

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/edit.html.erb
<h1>EDIT</h1>
<p>formulario de edición</p>

<%= form_for @blog, url: blog_path(@blog), method: :put do |f| %>
  <div>
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/blog/index.html.erb
<h1>BLOG</h1>

<div><%= link_to "Create post", new_blog_path %></div>
<br>
<hr>
<br>
<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Content</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.tittle %></td>
        <td><%= blog.content %></td>
        <td><%= link_to "Show", blog_path(blog.id) %></td>
        <td><%= link_to "Edit", edit_blog_path(blog.id) %></td>
        <td><%= link_to "Delete", blog_path(blog.id), method: :delete, data: {confirm: "¿estás seguro de eliminar este post?"} %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/blog/new.html.erb
<%= form_for @blog, url: blog_index_path, method: :post do |f| %>
  <div>
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/blog/partials/_articles.html.erb
<article class="">
  acá estan mis articles!!!
</article>

app/views/blog/partials/_header.html.erb
<h2>aquí estan mis lineas de header</h2>

app/views/blog/partials/_sidebar.html.erb
<div>este es el sidebar</div>

app/views/blog/show.html.erb
<h1>Detalles del Blog # <%= @blog.id %></h1>

<div><strong>Title: </strong> <%= @blog.tittle %> </div>
<div><strong>Content:</strong> <%= @blog.content %> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeraAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class:name %>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/about.html.erb
<h1>ABOUT</h1>

<p>somos una empresa dedicada al desarrollo de apps</p>

app/views/welcome/contact_us.html.erb
<h1>Contáctanos</h1>
<p>dirección: Cr 84F #3c 40</p>
<p>Telefono: 3017075465</p>


<%= form_for @welcome, url: ruta_path, method: :post do |f| %>
  <div>
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= @name %>

app/views/welcome/prices.html.erb
<h1>Prices</h1>

<h2>basico</h2>
<p>3`000.000</p>

<h2>Medio</h2>
<p>7`000.000</p>

<h2>avanzado</h2>
<p>13`000.000</p>